name: Push to Organization Repo

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "Bimalka Piyaruwan"
          git config --global user.email "bimalkapiyaruwan1998322@gmail.com"
      - name: Add remote and push to organization repo
        run: |
          git remote add org_repo https://github.com/ENTC18/getting-started.git
          git push org_repo main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
